# Generated by Django 5.1 on 2026-03-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('query', 'Consulta Realizada'), ('index_build', 'Construcción de Índice'), ('error', 'Error del Sistema'), ('config_change', 'Cambio de Configuración'), ('startup', 'Inicio del Sistema')], max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítico')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(help_text='Consulta original del usuario')),
                ('assistant_response', models.TextField(help_text='Respuesta generada por el sistema')),
                ('response_time', models.FloatField(blank=True, help_text='Tiempo de respuesta en segundos', null=True)),
                ('chunks_retrieved', models.IntegerField(default=0, help_text='Número de chunks recuperados del índice')),
                ('context_used', models.TextField(blank=True, help_text='Contexto recuperado del índice vectorial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='Puntuación de 1-5 si el usuario proporciona feedback', null=True)),
            ],
            options={
                'verbose_name': 'Registro de Consulta',
                'verbose_name_plural': 'Registros de Consultas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chatbot_mes_convers_b353f0_idx',
            old_name='chatbot_mes_conversa_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='chatbot_aud_event_t_b538d4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['severity', 'created_at'], name='chatbot_aud_severit_d2cd28_idx'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='query_logs', to='chatbot.conversation'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['created_at'], name='chatbot_que_created_a89e33_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['conversation'], name='chatbot_que_convers_70fa03_idx'),
        ),
    ]
