# Generated by Django 5.1 on 2026-03-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auditlog_querylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Dirección IP del cliente', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Dirección IP del cliente', max_length=45, null=True),
        ),
    ]
